name: Update gist with Code::Stats stats
on:
  push:
    branches:
      - master
      - reenable-workflow
  schedule:
    - cron: "*/10 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python codestats_box.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1083656c42c57de519b07dd8c1d77474
          CODE_STATS_USERNAME: kk5190
          STATS_TYPE: ${{ secrets.STATS_TYPE }}
